version: '3.9'

services:
    wordpress:
        #    image: wordpress:php${PHP_VERSION}
        container_name: ${PROJECT}-wordpress
        build:
            context: .
            dockerfile: wordpress.dockerfile
            args:
                - PHP_VERSION=php${PHP_VERSION}
        restart: always
        volumes:
            - ../:/var/www/html
            - ./php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        networks:
            - wordpress

    nginx:
        image: nginx:${NGINX_VERSION}
        container_name: ${PROJECT}-nginx
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ../:/var/www/html
        ports:
            - 80:80
            - 443:443
        networks:
            - wordpress

networks:
    wordpress:
        name: ${PROJECT}

volumes:
    db:
        name: ${PROJECT}
